### PR TITLE
Migrate CSS for Code block for TT1-block theme

### PR DESCRIPTION
**Pull request by pbking**
Change to support: https://github.com/WordPress/theme-experiments/issues/94

Reference [TwentyTwentyOne's styles](As expressed by TT1's CODE block styles: https://github.com/WordPress/twentytwentyone/blob/trunk/assets/sass/05-blocks/code/_style.scss) for design target.

image

* Supply default padding values for CODE block
* Supply default font size attribute to code block
* Supply default boarder attributes to code block

Note: There were previously dependencies on changes to Gutenberg to allow some of these changes.  The actual changes made were different from the original dependencies but the result was the same.

### CODE REVIEW

**Comment by carolinan** [comment]
There is a problem with the text color of the code block, in Twenty Twenty-One, it is being overwritten by the editor styles.
It would be useful to be able to set the text color.
_Probably a lot more useful than being able to set both padding and border radius._

Trac ticket:
https://core.trac.wordpress.org/ticket/51985

**Comment by scruffian** [comment]
As @carolinan suggested we should be able to add support for custom colors to this block like we have for others.

My preference would be to not ship the CSS for borders in the PR but wait for support to be added to Gutenberg.

**Comment by pbking** [comment]
This has been updated to depend completely on Global Styles for border styling.  With this (and its dependent change) the code block for TT1-blocks reaches feature parity with TwentyTwentyOne.

image

**Comment by carolinan** [comment]
I removed the font size because in Twenty Twenty-One the default size of 20px is used.

**Pull request merged**
