### PR TITLE
Empty Theme: Changed slug on html templates

### PR DESCRIPTION
**Pull request by MaggieCabrera**
This PR changes the slug used on html templates to be the one using dashes instead of underscores.

Closes https://github.com/WordPress/theme-experiments/issues/146

### CODE REVIEW

**Comment by kjellr** [comment]
This is working well! One thing I noticed though: The enqueue handles are written out using underscores, but usually those use dashes. Would it be possible to change that too? All the other strings in that file would still use underscores, so I know it may be tougher. 

Screen Shot 2020-12-17 at 11 49 25 AM

**Comment by kjellr** [comment]
Also, this is not really related, but it might make sense to not copy over the `README.md` file. Since that's not required for the new theme, and isn't modified by the script anyway.

**Comment by MaggieCabrera** [comment]
> This is working well! One thing I noticed though: The enqueue handles are written out using underscores, but usually those use dashes. Would it be possible to change that too? All the other strings in that file would still use underscores, so I know it may be tougher.
> 
> Screen Shot 2020-12-17 at 11 49 25 AM

I can totally do that, I thought the underscores were the default for the function names but it's easy to change them really.

**Comment by kjellr** [comment]
> I can totally do that, I thought the underscores were the default for the function names but it's easy to change them really.

It is the default for the function names — just not for the enqueue function handles ('two_words-alignments-style` would usually be `two-words-alignments-style` for example).

**Comment by MaggieCabrera** [comment]
> > I can totally do that, I thought the underscores were the default for the function names but it's easy to change them really.
> 
> It is the default for the function names — just not for the enqueue function handles (`two_words-alignments-style` would usually be `two-words-alignments-style` for example).

Oh yeah, I get what you mean! I'll try that

**Comment by MaggieCabrera** [comment]
This is ready for review. Regex are not my strong suit so please review away :D

**Review by kjellr — APPROVED** [review]
This works in my testing! Thanks, @MaggieCabrera!

**Pull request merged**
