### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by bph**
It explains, why there is nothing to see.
~DocumentsCleanShot 2021-03-02 at 12 39 43

### CODE REVIEW

**Comment by kjellr** [comment]
This makes sense. I wonder if this should be printed as a translatable string, but I might be overthinking it. 😄 I'll let someone else weigh in on that too.

**Comment by carolinan** [comment]
Yes all theme text strings need to be translation ready :)
Example https://github.com/WordPress/theme-experiments/blob/master/armando/index.php

**Comment by bph** [comment]
@carolinan and @kjellr Thank :-)

**Review by kjellr — APPROVED** [review]
Looks good to me. Thank you @bph!

**Pull request merged**
