### PR TITLE
Update README.md with What's Here

### PR DESCRIPTION
**Pull request by jffng**
This PR updates the readme with a table listing of the themes and the version they were last tested against.

### CODE REVIEW

**Comment by jffng** [comment]
Addresses part of #58.

**Comment by kjellr** [comment]
Awesome, this is a great start. Can you perhaps link each theme name to its directory?

**Comment by kjellr** [comment]
While you're in here, let's add a few more links to documentation too: 

Current: 


- [Block-based Theme Documentation (Experimental)](https://developer.wordpress.org/block-editor/developers/themes/block-based-themes/)
- [Full site editing development in the Gutenberg repo](https://github.com/WordPress/gutenberg/labels/%5BFeature%5D%20Full%20Site%20Editing)
- [Defining Content-Block Areas](https://make.wordpress.org/core/2019/09/05/defining-content-block-areas/)

Suggested: 

- [Block-based Themes Documentation](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/themes/block-based-themes.md)
- [experimental theme.json Documentation](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/themes/theme-json.md)
- [Block-based Theme Tutorial](https://developer.wordpress.org/block-editor/developers/themes/block-based-themes/)
- [Full site editing development in the Gutenberg repo](https://github.com/WordPress/gutenberg/labels/%5BFeature%5D%20Full%20Site%20Editing)

**Comment by jffng** [comment]
Good call, updated the resources section. 

Any additional changes feel free to commit directly and merge when you think it's in a good spot.

**Comment by kjellr** [comment]
Looks good, thank you!

**Review by kjellr — APPROVED** [review]

**Pull request merged**
