### PR TITLE
Update shape of theme.json: settings & styles as top-level keys

### PR DESCRIPTION
**Pull request by nosolosw**
:loudspeaker: **The changes have landed in Gutenberg master, so this is ready**

The goal of this PR is to serve as a testbed for the upcoming changes at https://github.com/WordPress/gutenberg/pull/28110

### CODE REVIEW

**Comment by nosolosw** [comment]
https://github.com/WordPress/gutenberg/pull/28110 is ready and will be merged soon (probably tomorrow). Should this PR be merged soon after so this repo is in sync with Gutenberg's main branch?

cc @kjellr @scruffian

**Comment by carolinan** [comment]
If we do that, the documentation must be updated to reflect that this version of the theme requires the development version of Gutenberg. 

It needs to be made very clear to users, including those who are testing FSE within the FSE outreach program, which version of the theme to use for testing, together with which version of Gutenberg.

**Comment by nosolosw** [comment]
Updated this to make it work with https://github.com/WordPress/gutenberg/pull/28533

**Comment by nosolosw** [comment]
I figured this PR could be useful for people to match the changes in https://github.com/WordPress/gutenberg/pull/28110 given that it has landed in `master` so I scoped it down to it.

Not sure how's the process but this can land safely.

There's now a separate https://github.com/WordPress/theme-experiments/pull/182 to serve a testbed for a new Gutenberg PR.

**Comment by kjellr** [comment]
My suggestion is that we merge this in to the version here (alongside a version bump), but do not upload this version to the theme repository until it's been merged into the plugin. 

I do think some sort of clarifying note in this repo may be helpful — something along the lines of "The version of the theme in this repository may rely on Gutenberg features that have not yet made it into an official release."

**Comment by nosolosw** [comment]
I wanted to share that the second PR to update the theme.json shape also landed in Gutenberg and will be part of 9.9 https://github.com/WordPress/gutenberg/pull/28533 This will still require the plugin to work and won't be part of WordPress 5.7.

Given that the two Gutenberg PRs already landed I think it's best to close this PR and land https://github.com/WordPress/theme-experiments/pull/175 instead (it has all the changes already).

**Pull request merged**
